"""
Conference and journal format specifications.
Each entry defines the exact formatting rules an agent must satisfy.
"""

from models import ConferenceFormat, FormatSpec, SectionType

CONFERENCE_SPECS: dict[ConferenceFormat, FormatSpec] = {

    ConferenceFormat.IEEE: FormatSpec(
        conference=ConferenceFormat.IEEE,
        required_sections=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.METHODOLOGY,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        forbidden_sections=[],
        section_order=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.ACKNOWLEDGMENTS,
            SectionType.REFERENCES,
        ],
        max_abstract_words=150,
        reference_style="IEEE",
        author_format="F. Last",
        columns=2,
        title_case="title_case",
        max_pages=8,
        citation_style="numeric",
    ),

    ConferenceFormat.ACM: FormatSpec(
        conference=ConferenceFormat.ACM,
        required_sections=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.METHODOLOGY,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        forbidden_sections=[],
        section_order=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.ACKNOWLEDGMENTS,
            SectionType.REFERENCES,
        ],
        max_abstract_words=200,
        reference_style="ACM",
        author_format="First Last",
        columns=2,
        title_case="title_case",
        max_pages=10,
        citation_style="numeric",
    ),

    ConferenceFormat.NeurIPS: FormatSpec(
        conference=ConferenceFormat.NeurIPS,
        required_sections=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        forbidden_sections=[],
        section_order=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.ACKNOWLEDGMENTS,
            SectionType.REFERENCES,
            SectionType.APPENDIX,
        ],
        max_abstract_words=250,
        reference_style="APA",
        author_format="First Last",
        columns=1,
        title_case="title_case",
        max_pages=9,
        citation_style="author_year",
    ),

    ConferenceFormat.ICML: FormatSpec(
        conference=ConferenceFormat.ICML,
        required_sections=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        forbidden_sections=[],
        section_order=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.ACKNOWLEDGMENTS,
            SectionType.REFERENCES,
            SectionType.APPENDIX,
        ],
        max_abstract_words=200,
        reference_style="APA",
        author_format="First Last",
        columns=2,
        title_case="title_case",
        max_pages=8,
        citation_style="author_year",
    ),

    ConferenceFormat.AAAI: FormatSpec(
        conference=ConferenceFormat.AAAI,
        required_sections=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        forbidden_sections=[],
        section_order=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        max_abstract_words=150,
        reference_style="AAAI",
        author_format="First Last",
        columns=2,
        title_case="title_case",
        max_pages=7,
        citation_style="author_year",
    ),

    ConferenceFormat.ARXIV: FormatSpec(
        conference=ConferenceFormat.ARXIV,
        required_sections=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.CONCLUSION,
            SectionType.REFERENCES,
        ],
        forbidden_sections=[],
        section_order=[
            SectionType.ABSTRACT,
            SectionType.INTRODUCTION,
            SectionType.RELATED_WORK,
            SectionType.METHODOLOGY,
            SectionType.EXPERIMENTS,
            SectionType.RESULTS,
            SectionType.CONCLUSION,
            SectionType.ACKNOWLEDGMENTS,
            SectionType.REFERENCES,
            SectionType.APPENDIX,
        ],
        max_abstract_words=300,
        reference_style="APA",
        author_format="First Last",
        columns=1,
        title_case="title_case",
        max_pages=None,
        citation_style="author_year",
    ),
}


def get_spec(fmt: ConferenceFormat) -> FormatSpec:
    return CONFERENCE_SPECS[fmt]
